export const JOURNALS = [
  { tier: "1", journal: "Anatolian Studies", issn: "2048-0849" },
  { tier: "1", journal: "Arab Law Quarterly", issn: "1573-0255" },
  { tier: "1", journal: "Arab Media & Society", issn: "1687-7721" },
  { tier: "1", journal: "Arab Studies Journal", issn: "2328-9627" },
  { tier: "1", journal: "Arab Studies Quarterly", issn: "2043-6920" },
  { tier: "1", journal: "Arabica", issn: "1570-0585" },
  { tier: "1", journal: "British Journal of Middle Eastern Studies", issn: "1469-3542" },
  { tier: "1", journal: "British Museum Studies in Ancient Egypt and Sudan", issn: "2049-5021" },
  { tier: "1", journal: "Contemporary Arab Affairs", issn: "1755-0920" },
  { tier: "1", journal: "Dead Sea Discoveries", issn: "1568-5179" },
  { tier: "1", journal: "International Journal of Middle East Studies", issn: "1471-6380" },
  { tier: "1", journal: "Iran", issn: "2396-9202" },
  { tier: "1", journal: "Iran and the Caucasus", issn: "1573-384X" },
  { tier: "1", journal: "Iranian Studies", issn: "1475-4819" },
  { tier: "1", journal: "Iraq", issn: "2053-4744" },
  { tier: "1", journal: "Islamic Law and Society", issn: "1568-5195" },
  { tier: "1", journal: "Israel Studies", issn: "1527-201X" },
  { tier: "1", journal: "Journal of Arabic and Islamic Studies", issn: "0806-198X" },
  { tier: "1", journal: "Journal of Arabic Literature", issn: "1570-064X" },
  { tier: "1", journal: "Journal of Cuneiform Studies", issn: "2325-6737" },
  { tier: "1", journal: "Journal of Islamic Studies", issn: "1471-6917" },
  { tier: "1", journal: "Journal of Middle East Women's Studies", issn: "1558-9579" },
  { tier: "1", journal: "Journal of Near Eastern Studies", issn: "1545-6978" },
  { tier: "1", journal: "Journal of Palestine Studies", issn: "1533-8614" },
  { tier: "1", journal: "Journal of Qur'anic Studies", issn: "1755-1730" },
  { tier: "1", journal: "Journal of the Economic and Social History of the Orient", issn: "1568-5209" },
  { tier: "1", journal: "Mamluk Studies Review", issn: "2563-4240" },
  { tier: "1", journal: "Mediterranean Politics", issn: "1471-6518" },
  { tier: "1", journal: "MELA Notes", issn: "2158-5180" },
  { tier: "1", journal: "Middle East Critique", issn: "1943-6157" },
  { tier: "1", journal: "Middle East Law and Governance", issn: "1876-3375" },
  { tier: "1", journal: "Middle East Policy", issn: "1475-4967" },
  { tier: "1", journal: "Middle East Quarterly", issn: "1564-2089" },
  { tier: "1", journal: "Middle East Report", issn: "2327-5782" },
  { tier: "1", journal: "Middle East Review of International Affairs", issn: "1565-8996" },
  { tier: "1", journal: "Middle Eastern Literatures", issn: "1475-2638" },
  { tier: "1", journal: "Middle Eastern Studies", issn: "1743-7881" },
  { tier: "1", journal: "Muqarnas", issn: "2211-8993" },
  { tier: "1", journal: "Near Eastern Archaeology", issn: "2325-5404" },
  { tier: "1", journal: "Proceedings of the Seminar for Arabian Studies", issn: "2058-5209" },
  { tier: "1", journal: "Review of Middle East Economics and Finance", issn: "1475-3693" },
  { tier: "1", journal: "The Middle East Journal", issn: "1940-3461" },
  { tier: "2", journal: "Alif: Journal of Comparative Poetics", issn: "2090-8830" },
  { tier: "2", journal: "Ars Orientalis", issn: "2328-1286" },
  { tier: "2", journal: "Bulletin of the American Society of Overseas Research", issn: "2161-8062" },
  { tier: "2", journal: "Bulletin of the School of Oriental and African Studies", issn: "1474-0699" },
  { tier: "2", journal: "Comparative Studies of South Asia, Africa and the Middle East", issn: "1548-226X" },
  { tier: "2", journal: "Constellations", issn: "1467-8675" },
  { tier: "2", journal: "Critical Studies on Terrorism", issn: "1753-9161" },
  { tier: "2", journal: "Defense and Peace Economics", issn: "1476-8267" },
  { tier: "2", journal: "Democratization", issn: "1743-890X" },
  { tier: "2", journal: "Development and Change", issn: "1467-7660" },
  { tier: "2", journal: "Dynamics of Asymmetric Conflict", issn: "1940-4611" },
  { tier: "2", journal: "Global Change Peace & Security", issn: "1478-1166" },
  { tier: "2", journal: "Government and Opposition", issn: "1477-7053" },
  { tier: "2", journal: "International Interactions", issn: "1547-7444" },
  { tier: "2", journal: "Journal of Economic Cooperation and Development", issn: "2789-0791" },
  { tier: "2", journal: "Journal of Globalization and Development", issn: "1948-1837" },
  { tier: "2", journal: "Journal of the American Oriental Society", issn: "2169-2408" },
  { tier: "2", journal: "Law & Development Review", issn: "1943-3867" },
  { tier: "2", journal: "Oriens", issn: "1877-8372" },
  { tier: "2", journal: "Oxford Development Studies", issn: "1469-9966" },
  { tier: "2", journal: "Progress in Development Studies", issn: "1477-027X" },
  { tier: "2", journal: "Review of African Political Economy", issn: "1740-1720" },
  { tier: "2", journal: "Security Studies", issn: "1556-1852" },
  { tier: "2", journal: "Studies in Conflict & Terrorism", issn: "1521-0731" },
  { tier: "2", journal: "Terrorism and Political Violence", issn: "1556-1836" },
  { tier: "2", journal: "The Developing Economies", issn: "1746-1049" },
  { tier: "2", journal: "The Journal of Development Studies", issn: "1743-9140" },
  { tier: "2", journal: "The Washington Quarterly", issn: "1530-9177" },
  { tier: "2", journal: "Third World Quarterly", issn: "1360-2241" },
  { tier: "3", journal: "Acta Politica", issn: "1741-1416" },
  { tier: "3", journal: "American Anthropologist", issn: "1548-1433" },
  { tier: "3", journal: "American Economic Review", issn: "1944-7981" },
  { tier: "3", journal: "American Ethnologist", issn: "1548-1425" },
  { tier: "3", journal: "American Journal of Political Science", issn: "1540-5907" },
  { tier: "3", journal: "American Political Science Review", issn: "1537-5943" },
  { tier: "3", journal: "Anthropology & Education Quarterly", issn: "1548-1492" },
  { tier: "3", journal: "British Journal of Political Science", issn: "1469-2112" },
  { tier: "3", journal: "Comparative Political Studies", issn: "1552-3829" },
  { tier: "3", journal: "Comparative Politics", issn: "2151-6227" },
  { tier: "3", journal: "Comparative Studies in Society and History", issn: "1475-2999" },
  { tier: "3", journal: "Critical Review", issn: "1933-8007" },
  { tier: "3", journal: "Economic Affairs", issn: "1468-0270" },
  { tier: "3", journal: "Economic Development Quarterly", issn: "1552-3543" },
  { tier: "3", journal: "Economics and Politics", issn: "1468-0343" },
  { tier: "3", journal: "Electoral Studies", issn: "1873-6890" },
  { tier: "3", journal: "European Journal of International Relations", issn: "1460-3713" },
  { tier: "3", journal: "European Journal of Political Research", issn: "1475-6765" },
  { tier: "3", journal: "European Political Science Review", issn: "1755-7747" },
  { tier: "3", journal: "Georgetown Journal of International Affairs", issn: "2471-8831" },
  { tier: "3", journal: "Global Media Journal", issn: "1550-7521" },
  { tier: "3", journal: "International Affairs", issn: "1468-2346" },
  { tier: "3", journal: "International Journal of Urban and Regional Research", issn: "1468-2427" },
  { tier: "3", journal: "International Organization", issn: "1531-5088" },
  { tier: "3", journal: "International Political Science Review", issn: "1460-373X" },
  { tier: "3", journal: "International Political Sociology", issn: "1749-5687" },
  { tier: "3", journal: "International Politics", issn: "1740-3898" },
  { tier: "3", journal: "International Relations", issn: "1741-2862" },
  { tier: "3", journal: "International Studies", issn: "0974-0082" },
  { tier: "3", journal: "International Studies Perspectives", issn: "1528-3585" },
  { tier: "3", journal: "International Studies Quarterly", issn: "1468-2478" },
  { tier: "3", journal: "International Studies Review", issn: "1468-2486" },
  { tier: "3", journal: "Journal of Civil Society", issn: "1744-8697" },
  { tier: "3", journal: "Journal of Contemporary History", issn: "1461-7250" },
  { tier: "3", journal: "Journal of Democracy", issn: "1086-3214" },
  { tier: "3", journal: "Journal of Developing Societies", issn: "1745-2546" },
  { tier: "3", journal: "Journal of Economic Literature", issn: "2328-8175" },
  { tier: "3", journal: "Journal of Economic Policy Reform", issn: "1748-7889" },
  { tier: "3", journal: "Journal of Institutional Economics", issn: "1744-137X" },
  { tier: "3", journal: "Journal of Peace Research", issn: "1460-3578" },
  { tier: "3", journal: "Journal of Political Economy", issn: "1537-534X" },
  { tier: "3", journal: "Journal of Social History", issn: "1527-1897" },
  { tier: "3", journal: "Millennium: Journal of International Studies", issn: "1477-9021" },
  { tier: "3", journal: "New Global Studies", issn: "1940-0004" },
  { tier: "3", journal: "New Left Review", issn: "1749-9976" },
  { tier: "3", journal: "Participations: Journal of Audience & Reception Studies", issn: "1749-8716" },
  { tier: "3", journal: "Perspectives on Politics", issn: "1541-0986" },
  { tier: "3", journal: "Political Science Quarterly", issn: "1538-165X" },
  { tier: "3", journal: "Political Studies", issn: "1467-9248" },
  { tier: "3", journal: "Politics & Society", issn: "1552-7514" },
  { tier: "3", journal: "Politics, Philosophy & Economics", issn: "1741-3060" },
  { tier: "3", journal: "Polity", issn: "1744-1684" },
  { tier: "3", journal: "PS: Political Science & Politics", issn: "1537-5935" },
  { tier: "3", journal: "Review of International Political Economy", issn: "1466-4526" },
  { tier: "3", journal: "Review of Political Economy", issn: "1469-9494" },
  { tier: "3", journal: "Review of Radical Political Economics", issn: "1552-8502" },
  { tier: "3", journal: "Social & Legal Studies", issn: "1461-7390" },
  { tier: "3", journal: "The American Journal of Economics and Sociology", issn: "1536-7150" },
  { tier: "3", journal: "The Economic Journal", issn: "1468-0297" },
  { tier: "3", journal: "The European Journal of Development Research", issn: "1743-9728" },
  { tier: "3", journal: "The Journal of Politics", issn: "1468-2508" },
  { tier: "3", journal: "World Politics", issn: "1086-3338" },
];

export const PART_MAP = {
  "Arab Law Quarterly": "Part 1",
  "Arab Media & Society": "Part 1",
  "Arab Studies Journal": "Part 1",
  "Arab Studies Quarterly": "Part 1",
  "British Journal of Middle Eastern Studies": "Part 1",
  "Comparative Studies of South Asia, Africa and the Middle East": "Part 1",
  "Contemporary Arab Affairs": "Part 1",
  "International Journal of Middle East Studies": "Part 1",
  "Israel Studies": "Part 1",
  "Journal of Middle East Women's Studies": "Part 1",
  "Journal of Palestine Studies": "Part 1",
  "Mediterranean Politics": "Part 1",
  "Middle East Critique": "Part 1",
  "Middle East Law and Governance": "Part 1",
  "Middle East Policy": "Part 1",
  "Middle East Quarterly": "Part 1",
  "Middle East Report": "Part 1",
  "Middle East Review of International Affairs": "Part 1",
  "The Middle East Journal": "Part 1",
  "Alif: Journal of Comparative Poetics": "Part 2",
  "Anatolian Studies": "Part 2",
  "Arabica": "Part 2",
  "Ars Orientalis": "Part 2",
  "British Museum Studies in Ancient Egypt and Sudan": "Part 2",
  "Bulletin of the American Society of Overseas Research": "Part 2",
  "Bulletin of the School of Oriental and African Studies": "Part 2",
  "Comparative Studies in Society and History": "Part 2",
  "Dead Sea Discoveries": "Part 2",
  "Iran": "Part 2",
  "Iran and the Caucasus": "Part 2",
  "Iranian Studies": "Part 2",
  "Iraq": "Part 2",
  "Islamic Law and Society": "Part 2",
  "Journal of Arabic Literature": "Part 2",
  "Journal of Arabic and Islamic Studies": "Part 2",
  "Journal of Contemporary History": "Part 2",
  "Journal of Cuneiform Studies": "Part 2",
  "Journal of Islamic Studies": "Part 2",
  "Journal of Near Eastern Studies": "Part 2",
  "Journal of Qur'anic Studies": "Part 2",
  "Journal of Social History": "Part 2",
  "Journal of the American Oriental Society": "Part 2",
  "Journal of the Economic and Social History of the Orient": "Part 2",
  "MELA Notes": "Part 2",
  "Mamluk Studies Review": "Part 2",
  "Middle Eastern Literatures": "Part 2",
  "Middle Eastern Studies": "Part 2",
  "Muqarnas": "Part 2",
  "Near Eastern Archaeology": "Part 2",
  "Oriens": "Part 2",
  "Proceedings of the Seminar for Arabian Studies": "Part 2",
  "Critical Studies on Terrorism": "Part 3",
  "Defense and Peace Economics": "Part 3",
  "Democratization": "Part 3",
  "Dynamics of Asymmetric Conflict": "Part 3",
  "Global Change Peace & Security": "Part 3",
  "Government and Opposition": "Part 3",
  "Journal of Peace Research": "Part 3",
  "Security Studies": "Part 3",
  "Studies in Conflict & Terrorism": "Part 3",
  "Studies in Conflict &Terrorism": "Part 3",
  "Terrorism and Political Violence": "Part 3",
  "Acta Politica": "Part 4",
  "American Anthropologist": "Part 4",
  "American Economic Review": "Part 4",
  "American Ethnologist": "Part 4",
  "American Journal of Political Science": "Part 4",
  "American Political Science Review": "Part 4",
  "Anthropology & Education Quarterly": "Part 4",
  "British Journal of Political Science": "Part 4",
  "Comparative Political Studies": "Part 4",
  "Comparative Politics": "Part 4",
  "Constellations": "Part 4",
  "Critical Review": "Part 4",
  "Development and Change": "Part 4",
  "Economic Affairs": "Part 4",
  "Economic Development Quarterly": "Part 4",
  "Economics and Politics": "Part 4",
  "Electoral Studies": "Part 4",
  "European Journal of Development Research": "Part 4",
  "European Journal of International Relations": "Part 4",
  "European Journal of Political Research": "Part 4",
  "European Political Science Review": "Part 4",
  "Georgetown Journal of International Affairs": "Part 4",
  "Global Media Journal": "Part 4",
  "International Affairs": "Part 4",
  "International Interactions": "Part 4",
  "International Journal of Urban and Regional Research": "Part 4",
  "International Organization": "Part 4",
  "International Political Science Review": "Part 4",
  "International Political Sociology": "Part 4",
  "International Politics": "Part 4",
  "International Relations": "Part 4",
  "International Studies": "Part 4",
  "International Studies Perspectives": "Part 4",
  "International Studies Quarterly": "Part 4",
  "International Studies Review": "Part 4",
  "Journal of Civil Society": "Part 4",
  "Journal of Democracy": "Part 4",
  "Journal of Developing Societies": "Part 4",
  "Journal of Economic Cooperation and Development": "Part 4",
  "Journal of Economic Literature": "Part 4",
  "Journal of Economic Policy Reform": "Part 4",
  "Journal of Globalization and Development": "Part 4",
  "Journal of Institutional Economics": "Part 4",
  "Journal of Political Economy": "Part 4",
  "Law & Development Review": "Part 4",
  "Millennium: Journal of International Studies": "Part 4",
  "New Global Studies": "Part 4",
  "New Left Review": "Part 4",
  "Oxford Development Studies": "Part 4",
  "PS: Political Science & Politics": "Part 4",
  "Participations: Journal of Audience & Reception Studies": "Part 4",
  "Perspectives on Politics": "Part 4",
  "Political Science Quarterly": "Part 4",
  "Political Studies": "Part 4",
  "Politics & Society": "Part 4",
  "Politics, Philosophy & Economics": "Part 4",
  "Polity": "Part 4",
  "Progress in Development Studies": "Part 4",
  "Review of African Political Economy": "Part 4",
  "Review of International Political Economy": "Part 4",
  "Review of Middle East Economics and Finance": "Part 4",
  "Review of Political Economy": "Part 4",
  "Review of Radical Political Economics": "Part 4",
  "Social & Legal Studies": "Part 4",
  "The American Journal of Economics and Sociology": "Part 4",
  "The Developing Economies": "Part 4",
  "The Economic Journal": "Part 4",
  "The European Journal of Development Research": "Part 4",
  "The Journal of Development Studies": "Part 4",
  "The Journal of Politics": "Part 4",
  "The Washington Quarterly": "Part 4",
  "Third World Quarterly": "Part 4",
  "World Politics": "Part 4",
};

export const PART_COLORS = {
  "Part 1": { bg: "#FFF3E0", border: "#FF6600", text: "#E65100" },
  "Part 2": { bg: "#E3F2FD", border: "#2196F3", text: "#0D47A1" },
  "Part 3": { bg: "#E8F5E9", border: "#4CAF50", text: "#1B5E20" },
  "Part 4": { bg: "#F3E5F5", border: "#9C27B0", text: "#4A148C" },
};
