// PRAR App data constants.
//
// JOURNALS was removed in the Approach-B migration — the master journal
// list now lives in prar.master_journals and is loaded via lib/db.js.
//
// PART_MAP and PART_COLORS are kept here for client-side use:
//   - Stage 3 uses PART_COLORS for per-part cell tinting.
//   - PART_MAP is a fallback only; the backend stamps `part` on each
//     article in /fetch, so the frontend rarely needs to compute it.

export const PART_MAP = {
  "Arab Law Quarterly": "Part 1",
  "Arab Media & Society": "Part 1",
  "Arab Studies Journal": "Part 1",
  "Arab Studies Quarterly": "Part 1",
  "British Journal of Middle Eastern Studies": "Part 1",
  "Comparative Studies of South Asia, Africa and the Middle East": "Part 1",
  "Contemporary Arab Affairs": "Part 1",
  "International Journal of Middle East Studies": "Part 1",
  "Israel Studies": "Part 1",
  "Journal of Middle East Women's Studies": "Part 1",
  "Journal of Palestine Studies": "Part 1",
  "Mediterranean Politics": "Part 1",
  "Middle East Critique": "Part 1",
  "Middle East Law and Governance": "Part 1",
  "Middle East Policy": "Part 1",
  "Middle East Quarterly": "Part 1",
  "Middle East Report": "Part 1",
  "Middle East Review of International Affairs": "Part 1",
  "The Middle East Journal": "Part 1",
  "Alif: Journal of Comparative Poetics": "Part 2",
  "Anatolian Studies": "Part 2",
  "Arabica": "Part 2",
  "Ars Orientalis": "Part 2",
  "British Museum Studies in Ancient Egypt and Sudan": "Part 2",
  "Bulletin of the American Society of Overseas Research": "Part 2",
  "Bulletin of the School of Oriental and African Studies": "Part 2",
  "Comparative Studies in Society and History": "Part 2",
  "Dead Sea Discoveries": "Part 2",
  "Iran": "Part 2",
  "Iran and the Caucasus": "Part 2",
  "Iranian Studies": "Part 2",
  "Iraq": "Part 2",
  "Islamic Law and Society": "Part 2",
  "Journal of Arabic Literature": "Part 2",
  "Journal of Arabic and Islamic Studies": "Part 2",
  "Journal of Contemporary History": "Part 2",
  "Journal of Cuneiform Studies": "Part 2",
  "Journal of Islamic Studies": "Part 2",
  "Journal of Near Eastern Studies": "Part 2",
  "Journal of Qur'anic Studies": "Part 2",
  "Journal of Social History": "Part 2",
  "Journal of the American Oriental Society": "Part 2",
  "Journal of the Economic and Social History of the Orient": "Part 2",
  "MELA Notes": "Part 2",
  "Mamluk Studies Review": "Part 2",
  "Middle Eastern Literatures": "Part 2",
  "Middle Eastern Studies": "Part 2",
  "Muqarnas": "Part 2",
  "Near Eastern Archaeology": "Part 2",
  "Oriens": "Part 2",
  "Proceedings of the Seminar for Arabian Studies": "Part 2",
  "Critical Studies on Terrorism": "Part 3",
  "Defense and Peace Economics": "Part 3",
  "Democratization": "Part 3",
  "Dynamics of Asymmetric Conflict": "Part 3",
  "Global Change Peace & Security": "Part 3",
  "Government and Opposition": "Part 3",
  "Journal of Peace Research": "Part 3",
  "Security Studies": "Part 3",
  "Studies in Conflict & Terrorism": "Part 3",
  "Studies in Conflict &Terrorism": "Part 3",
  "Terrorism and Political Violence": "Part 3",
  "Acta Politica": "Part 4",
  "American Anthropologist": "Part 4",
  "American Economic Review": "Part 4",
  "American Ethnologist": "Part 4",
  "American Journal of Political Science": "Part 4",
  "American Political Science Review": "Part 4",
  "Anthropology & Education Quarterly": "Part 4",
  "British Journal of Political Science": "Part 4",
  "Comparative Political Studies": "Part 4",
  "Comparative Politics": "Part 4",
  "Constellations": "Part 4",
  "Critical Review": "Part 4",
  "Development and Change": "Part 4",
  "Economic Affairs": "Part 4",
  "Economic Development Quarterly": "Part 4",
  "Economics and Politics": "Part 4",
  "Electoral Studies": "Part 4",
  "European Journal of Development Research": "Part 4",
  "European Journal of International Relations": "Part 4",
  "European Journal of Political Research": "Part 4",
  "European Political Science Review": "Part 4",
  "Georgetown Journal of International Affairs": "Part 4",
  "Global Media Journal": "Part 4",
  "International Affairs": "Part 4",
  "International Interactions": "Part 4",
  "International Journal of Urban and Regional Research": "Part 4",
  "International Organization": "Part 4",
  "International Political Science Review": "Part 4",
  "International Political Sociology": "Part 4",
  "International Politics": "Part 4",
  "International Relations": "Part 4",
  "International Studies": "Part 4",
  "International Studies Perspectives": "Part 4",
  "International Studies Quarterly": "Part 4",
  "International Studies Review": "Part 4",
  "Journal of Civil Society": "Part 4",
  "Journal of Democracy": "Part 4",
  "Journal of Developing Societies": "Part 4",
  "Journal of Economic Cooperation and Development": "Part 4",
  "Journal of Economic Literature": "Part 4",
  "Journal of Economic Policy Reform": "Part 4",
  "Journal of Globalization and Development": "Part 4",
  "Journal of Institutional Economics": "Part 4",
  "Journal of Political Economy": "Part 4",
  "Law & Development Review": "Part 4",
  "Millennium: Journal of International Studies": "Part 4",
  "New Global Studies": "Part 4",
  "New Left Review": "Part 4",
  "Oxford Development Studies": "Part 4",
  "PS: Political Science & Politics": "Part 4",
  "Participations: Journal of Audience & Reception Studies": "Part 4",
  "Perspectives on Politics": "Part 4",
  "Political Science Quarterly": "Part 4",
  "Political Studies": "Part 4",
  "Politics & Society": "Part 4",
  "Politics, Philosophy & Economics": "Part 4",
  "Polity": "Part 4",
  "Progress in Development Studies": "Part 4",
  "Review of African Political Economy": "Part 4",
  "Review of International Political Economy": "Part 4",
  "Review of Middle East Economics and Finance": "Part 4",
  "Review of Political Economy": "Part 4",
  "Review of Radical Political Economics": "Part 4",
  "Social & Legal Studies": "Part 4",
  "The American Journal of Economics and Sociology": "Part 4",
  "The Developing Economies": "Part 4",
  "The Economic Journal": "Part 4",
  "The European Journal of Development Research": "Part 4",
  "The Journal of Development Studies": "Part 4",
  "The Journal of Politics": "Part 4",
  "The Washington Quarterly": "Part 4",
  "Third World Quarterly": "Part 4",
  "World Politics": "Part 4",
};

export const PART_COLORS = {
  "Part 1": { bg: "#FFF3E0", border: "#FF6600", text: "#E65100" },
  "Part 2": { bg: "#E3F2FD", border: "#2196F3", text: "#0D47A1" },
  "Part 3": { bg: "#E8F5E9", border: "#4CAF50", text: "#1B5E20" },
  "Part 4": { bg: "#F3E5F5", border: "#9C27B0", text: "#4A148C" },
};
